### ISSUE TITLE
Home link is not clickable when is less than 750px

### ISSUE THREAD

**Issue by jwald1** [Xiaohong-Deng/mooqita-icccg#14]

**Comment by Xiaohong-Deng** [comment]
@jwald1 Oh, yes, it is supposed to take you back to the home page. You can achieve that by clicking the **ICCCG** on the upper left corner. We'll tight up those loose ends that won't get in your way at the end of the day. Is it ok with you?

What does 750px mean? Are you designing css style for pad or smart phone screen? Is it necessary now?

**Comment by jwald1** [comment]
ICCG isn't working too. It's not necessary to provide a separate design for tablet devices, but it has to be functional at a minimum. I attached a screenshot of a browser with a width of 750px
![Screen Shot 2017-08-24 at 5.13.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598a35d4a585de001a0271d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456f76b7191a37df113284f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ee4d9640a7d973c40a4b0d717b901ba23824ed4b3bd8c49d2f42f67b6d5db1063474f4dcbed5727a39841c95df648e74f5ca6153261e7722431.png)

**Comment by Xiaohong-Deng** [comment]
I see what you means. That's something I didn't thought of before and haven't encountered thus far. Can we just assume people use the app when maxmizing the browser? I might have to look for a different css template if I were to solve it.

**Comment by jwald1** [comment]
We might do that, but it will better if we could support smaller screens too.

**Comment by Xiaohong-Deng** [comment]
@jwald1 Aha. I might have found a quick fix. Let me try and inform you.
