### ISSUE TITLE
ActionCable related problems

### ISSUE THREAD

**Issue by Xiaohong-Deng** [Xiaohong-Deng/mooqita-icccg#17]
All ac problems go here.

The probelms I have now are
1. if we have many chat rooms and only one defined `message_channel` and `stream_from 'messages'`, how do we make sure only users in chatroom **A** see messages from users in the room, not from users of other rooms. Also how they ensure they don't send their messages to other rooms?
2. What are the important variables or objects in a particular channel? In which methods i can access them? For example I want to access 'messages' from `stream_from 'messages'` that sits in redis.

**Comment by jwald1** [comment]
> if we have many chat rooms

Please explain how you have many chat rooms, so I can try to answer your question.

**Comment by Xiaohong-Deng** [comment]
@jwald1 It's a common setting in chatroom apps. I use it to understand actioncable better. For example, we should have room Python, Ruby and Java for developers who prefer those languages respectively.

**Comment by jwald1** [comment]
- There's only **one** channel instance/store in Redis, but **many connection instances**.
-  Each connection can be subscribed to many channels.

When you say `stream_from` you are like creating a sub channel (if it doesn't exist yet) and subscribing that connection to it.

It's helpful to think of `stream_from` as subscribing to a channel.

Hope this helps

**Comment by Xiaohong-Deng** [comment]
@jwald1 right, we can `stream_from 'messages_#{chatroom.id}'` and broadcast to `messages_#{chatroom.id}` in controller.

**Comment by Xiaohong-Deng** [comment]
no longer a problem.
