### ISSUE TITLE
Random Document

### ISSUE THREAD

**Issue by jwald1** [Xiaohong-Deng/mooqita-icccg#19]
To play ICCCG, we need a document to play with.

Here is my suggestion:
The `Document` should have a method `get_random(game)` which takes a `game` instance.

`get_random` should return a random document that none of the game.players have seen unless it does not have any documents besides that.

**Comment by Rojo** [comment]
@jwald1 How should the document be returned? Should it return a Document instance, letting the Document model handle all its properties or a JSON object would be better (as if the document was obtained from an external service)?

**Comment by jwald1** [comment]
I think it should return a `Document` instance. And the `Document` should have methods like `#text`or/and `#header` etc.

**Comment by Xiaohong-Deng** [comment]
@jwald1 this is a small feature and I did it before. All the work related to the ticket is in the model right? I can do the seeding, too.

**Comment by jwald1** [comment]
I'm not working on it. I think going forward when someone starts working on an issue he should add himself as an assignee.

**Comment by Rojo** [comment]
@jwald1 @Xiaohong-Deng Praveen asked to have available at least 20 documents from https://en.wikipedia.org/wiki/Aesop%27s_Fables#List_of_some_fables_by_Aesop

**Comment by Rojo** [comment]
@Xiaohong-Deng have you started working on this feature? I can help to prepare the documents for to be seed into the DB.

**Comment by jwald1** [comment]
I think we should add markdown support for the document

**Comment by Xiaohong-Deng** [comment]
@Rojo I planned to use gibberish docs. Same for us developers. Those docs won't make any difference to us in terms of testing or determining if the app is failing. Maybe Praveen wants to play, but it's irrelevant to this feature. are you gonna put them in the `seed.rb`? Or put them in separate files and read files in `seed.rb`? I think the latter is a good case for you to create an separate PR.

**Comment by Rojo** [comment]
@jwald1 That would be nice, but it is an enhancement, not something really needed for this stage.

**Comment by Rojo** [comment]
@Xiaohong-Deng I'll set separated text files to be loaded when `seed.rb` is called.

**Comment by Xiaohong-Deng** [comment]
@jwald1 I don't think avoiding duplication is a good idea here. If a player read the doc before but this time he is playing with different people, I don't see why not. if a player read it before as a judge or reader and is playing as a guesser this time then dups could be problematic. When and how to avoid dups here is a complex problem and should be deferred for now.

**Comment by Rojo** [comment]
@jwald1 @Xiaohong-Deng Yep, implementing a filter like that for selecting documents will take some time. For now, returning a random document would work well.

**Comment by Xiaohong-Deng** [comment]
@jwald1 @Rojo Actually I have a pretty good and simple filter in mind. By the time a game is ended, we add the doc_id to `read_docs` for judge and reader. Every time we enter the gaming cycle, we use the `read_docs` for guesser to subset the database. Anyway, it's better to make it a standalone PR. Keeping PR small makes code review easier. For this PR I just do a simple random fetch.

**Comment by Xiaohong-Deng** [comment]
@jwald1 I think it's better leave which game should the random doc be attached to to controller instead of letting `document` model interfere other model's business. so `get_random(game)` to `self.get_random`.
