### ISSUE TITLE
Add user authentication

### ISSUE THREAD

**Issue by Xiaohong-Deng** [Xiaohong-Deng/mooqita-icccg#2]
My plan is to use `devise`, which gives you nice login and signup features by default. It also can be completed by manually implementing, but require more man hours.

Of course, before that I should create a model `User`

**Comment by jwald1** [comment]
I think it would be nice to offer guest login. What do you think?

**Comment by Xiaohong-Deng** [comment]
@jwald1 You mean anonymous player being able to play? I don't know how to handle it. The app won't be able to tell who is the players playing. A random visiter could access the game by entering the specific URL to the game. The game object won't be able to tell the difference. Remember the user is authenticated by its `session[:id]`. Maybe it's doable at the cost of adding complexity. Can you design a plausible strategy to implement it?

**Comment by jwald1** [comment]
Agree, it will way too complex.
