### ISSUE TITLE
Game Flow Chart

### ISSUE THREAD

**Issue by jwald1** [Xiaohong-Deng/mooqita-icccg#20]
It will be helpful if one of us can draw a flow chart of the game steps or just write a list of the steps.

**Comment by Rojo** [comment]
I can work on this later today. As a start point, we have this diagram from the article:

![iccg flow diagram from article](https://user-images.githubusercontent.com/92138/29796581-82076958-8c17-11e7-8509-63f3bce8a1e2.png)

**Comment by Rojo** [comment]
* After all the player have joined, a new game starts, assigning the player a role at random:
* `reader` and `judge` can see the document content and the whiteboard.
![1-reader-judge-view](https://user-images.githubusercontent.com/92138/29812349-df1a2618-8c6b-11e7-8d8d-456b39b56124.png)
* `guesser` can only see the whiteboard.
![2-guesser-view](https://user-images.githubusercontent.com/92138/29812354-df29cb0e-8c6b-11e7-8c6b-572a5dff099b.png)
* At random, a player from `reader` and `guesser` is chosen to make a question about the document.
![3-question-input](https://user-images.githubusercontent.com/92138/29812350-df1bc09a-8c6b-11e7-9c72-afaf40d1ce31.png)
* When a question is made, `reader` and `guesser` are asked to answer the question.
![4-answer-input](https://user-images.githubusercontent.com/92138/29812352-df1e0364-8c6b-11e7-8777-93d89a0d7123.png)
* `judge` is presented with the question and the answers, having to choose which one is from the `reader`.
![5-answer-review](https://user-images.githubusercontent.com/92138/29812353-df2004e8-8c6b-11e7-878d-9d8e3c40b4e1.png)
* The whiteboard is updated.
* When the game is waiting for a user input, the other users should see a message informing of it.
![6-waiting-for-player](https://user-images.githubusercontent.com/92138/29812351-df1cc04e-8c6b-11e7-9e6f-144bb10f15ba.png)
* The cycle repeats selecting a player to make a new question until the **end game** condition is meet.
* The scoreboard is displayed.

What do you think @jwald1 @Xiaohong-Deng ?

**Comment by jwald1** [comment]
I think it's great! it also gives a good idea how the views should look. 

These three components need clarification:
1) Whiteboard (what should it show?),
 2) When does the game end? (what's the rules)
3)  Scoreboard, how should it look? Should it be the same for every player? What are the Score rules?

**Comment by jwald1** [comment]
> When the game is waiting for a user input, the other users should see a message informing of it.

It's a good idea to define those messages before coding.

**Comment by jwald1** [comment]
From the article diagram:
![Screen Shot 2017-08-29 at 2.24.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598a35d4a585de001a0271d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456fa6b7191a37af1102f4f5b585ecc3c4a4356bcbbd671f3e57862804e0ee4d9640a7d973c40a4b0d717b901ba23824ed4b3bd8c49d2f42f67b6d5db1063474f4dcbed5727a29941c95df64fe14e54a5113261e3752431.png)

What does "judge's score published to the whiteboard" mean?
Do all the players see just the judge's score?

**Comment by jwald1** [comment]
> The cycle repeats selecting a player to make a new question until the end game condition is meet.

Which players? Guesser and Reader?

**Comment by Rojo** [comment]
@jwald1 @Xiaohong-Deng 

1) Whiteboard shows the question-answer pairs generated during that game. At the start of the game, it should be empty.

I had not noticed the diagram telling the score points are published on the whiteboard. We could display the total score points at the top of it. There should be no problem showing the score to all the players so they can see how they're performing.

2) The diagram says "While the judge [gessings of the reader are] better than chance" the game continues. We could keep track of the _judge's_ last 5 attempts to identify the _reader_. If the performance is no better than randomly picking a player, the game ends.

Now, this may lead to complications on the experience for the gamers so we may include a feature to let the judge choose when to end a game or we could change the end game condition to a fixed amount of rounds depending on the complexity of the document, as someone suggested on Slack.

And yes, the person that makes the question is always chosen between the _reader_ and the _guesser_.

**Comment by jwald1** [comment]
@Rojo 
> We could display the total score points at the top of it

Just to be clear, each player will see their score? Guesser will see its score, and Reader will its score, etc.

**Comment by Rojo** [comment]
@jwald1 Let's show all the players score to everyone. We can ask for Praveen input on this while showing the demo.

**Comment by Xiaohong-Deng** [comment]
@Rojo Should this thread be updated by now? What's the Praveen's opinion? If we don't know how it should end we might as well repeat the game cycle twice then end it. Twice for the sake of making sure the game can cycle back to the beginning. 

We have the views. @jwald1 must have worked on it for days. What's your design in the back end? I can use some updates.

**Comment by Xiaohong-Deng** [comment]
@Rojo in the game cycle we are jumping between pages. we can either let the users click the button to go to the next page once the work on the current page is done or auto jump once the work is done. if we choose the former it's just the plain and simple MVC request/response cycles, if we choose the latter, javascript should be in charge of firing up redirect_to for players. for the latter it's my imagination. hope it's doable. I'm a javascript baby now. does it look plausible? any feedback is welcomed.

@jwald1 proposed a new model called `game_round` which I have difficulty understanding where should we put it in the gaming cycles. Do you have any idea on this?

**Comment by Rojo** [comment]
@Xiaohong-Deng I think he intends to use it to store some information generated by each game round (like who is the player that has the current action) and maybe use it to recover certain game state for _pause game_ and _rejoin game_ features.
