### ISSUE TITLE
Question and Answer Models

### ISSUE THREAD

**Issue by jwald1** [Xiaohong-Deng/mooqita-icccg#23]
The tables look like this:
![Screen Shot 2017-08-29 at 12.30.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598a35d4a585de001a0271d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6456fa6b7191a379ed0c2851415a4abc21254d58eeb9cb74fce36f34985619e8d8655621cf6c10fdb08a4ab707ba20884684e7b98b4ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be54d57a0103266e07f356e0a.png)

Question public API
   n/a

Answer public API

`.judge_identified_answer_for(question_object)`
- returns the answer that is judge_identified

`#judge_identify!`
 - This method will mark the answer as judge_identified
 - Should not allow two answers of the same question to be marked.

`#judge_identified?` Returns boolean

**Comment by Xiaohong-Deng** [comment]
answers should also have player_id, marking who wrote the answer so we compare that with `judge_identified` to tell who gets one point who lose one point.
