### ISSUE TITLE
First deploy on Heroku

### ISSUE THREAD

**Issue by Rojo** [Xiaohong-Deng/mooqita-icccg#24]
The first attempt to do a deploy on Heroku failed. Seems to be a problem related to the use of `yarn`. Will open a fix branch and work on it later, but here is the console output:

<details><pre>
± % git push heroku master                                                                                                                                                                               !46
Counting objects: 771, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (434/434), done.
Writing objects: 100% (771/771), 112.23 KiB | 0 bytes/s, done.
Total 771 (delta 391), reused 597 (delta 288)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote: 			Detected buildpacks: Ruby,Node.js
remote: 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.4.1
remote: -----> Installing dependencies using bundler 1.15.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.15.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/.........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        Fetching rake 12.0.0
remote:        Fetching concurrent-ruby 1.0.5
remote:        Fetching i18n 0.8.6
remote:        Installing i18n 0.8.6
remote:        Installing rake 12.0.0
remote:        Installing concurrent-ruby 1.0.5
remote:        Fetching minitest 5.10.3
remote:        Fetching thread_safe 0.3.6
remote:        Installing minitest 5.10.3
remote:        Installing thread_safe 0.3.6
remote:        Fetching builder 3.2.3
remote:        Fetching erubi 1.6.1
remote:        Installing erubi 1.6.1
remote:        Installing builder 3.2.3
remote:        Fetching mini_portile2 2.2.0
remote:        Installing mini_portile2 2.2.0
remote:        Fetching rack 2.0.3
remote:        Fetching nio4r 2.1.0
remote:        Fetching websocket-extensions 0.1.2
remote:        Installing nio4r 2.1.0 with native extensions
remote:        Installing websocket-extensions 0.1.2
remote:        Fetching mime-types-data 3.2016.0521
remote:        Installing rack 2.0.3
remote:        Installing mime-types-data 3.2016.0521
remote:        Fetching arel 8.0.0
remote:        Installing arel 8.0.0
remote:        Fetching execjs 2.7.0
remote:        Fetching bcrypt 3.1.11
remote:        Installing execjs 2.7.0
remote:        Installing bcrypt 3.1.11 with native extensions
remote:        Fetching rb-fsevent 0.10.2
remote:        Installing rb-fsevent 0.10.2
remote:        Fetching ffi 1.9.18
remote:        Installing ffi 1.9.18 with native extensions
remote:        Using bundler 1.15.2
remote:        Fetching coffee-script-source 1.12.2
remote:        Installing coffee-script-source 1.12.2
remote:        Fetching method_source 0.8.2
remote:        Installing method_source 0.8.2
remote:        Fetching thor 0.19.4
remote:        Installing thor 0.19.4
remote:        Fetching orm_adapter 0.5.0
remote:        Installing orm_adapter 0.5.0
remote:        Fetching pg 0.21.0
remote:        Installing pg 0.21.0 with native extensions
remote:        Fetching puma 3.9.1
remote:        Installing puma 3.9.1 with native extensions
remote:        Fetching redis 3.3.3
remote:        Installing redis 3.3.3
remote:        Fetching tilt 2.0.8
remote:        Installing tilt 2.0.8
remote:        Fetching tzinfo 1.2.3
remote:        Installing tzinfo 1.2.3
remote:        Fetching nokogiri 1.8.0
remote:        Installing nokogiri 1.8.0 with native extensions
remote:        Fetching websocket-driver 0.6.5
remote:        Installing websocket-driver 0.6.5 with native extensions
remote:        Fetching mime-types 3.1
remote:        Installing mime-types 3.1
remote:        Fetching rack-test 0.6.3
remote:        Installing rack-test 0.6.3
remote:        Fetching warden 1.2.7
remote:        Installing warden 1.2.7
remote:        Fetching sprockets 3.7.1
remote:        Installing sprockets 3.7.1
remote:        Fetching autoprefixer-rails 7.1.2.6
remote:        Installing autoprefixer-rails 7.1.2.6
remote:        Fetching uglifier 3.2.0
remote:        Installing uglifier 3.2.0
remote:        Fetching coffee-script 2.4.1
remote:        Installing coffee-script 2.4.1
remote:        Fetching rb-inotify 0.9.10
remote:        Installing rb-inotify 0.9.10
remote:        Fetching redis-unique-queue 1.0.3
remote:        Installing redis-unique-queue 1.0.3
remote:        Fetching activesupport 5.1.3
remote:        Installing activesupport 5.1.3
remote:        Fetching mail 2.6.6
remote:        Installing mail 2.6.6
remote:        Fetching sass-listen 4.0.0
remote:        Installing sass-listen 4.0.0
remote:        Fetching globalid 0.4.0
remote:        Installing globalid 0.4.0
remote:        Fetching activemodel 5.1.3
remote:        Installing activemodel 5.1.3
remote:        Fetching sass 3.5.1
remote:        Installing sass 3.5.1
remote:        Fetching activejob 5.1.3
remote:        Installing activejob 5.1.3
remote:        Fetching activerecord 5.1.3
remote:        Installing activerecord 5.1.3
remote:        Fetching bootstrap-sass 3.3.7
remote:        Installing bootstrap-sass 3.3.7
remote:        Fetching rails-dom-testing 2.0.3
remote:        Fetching loofah 2.0.3
remote:        Installing rails-dom-testing 2.0.3
remote:        Installing loofah 2.0.3
remote:        Fetching rails-html-sanitizer 1.0.3
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Fetching actionview 5.1.3
remote:        Installing actionview 5.1.3
remote:        Fetching actionpack 5.1.3
remote:        Installing actionpack 5.1.3
remote:        Fetching actioncable 5.1.3
remote:        Fetching actionmailer 5.1.3
remote:        Fetching railties 5.1.3
remote:        Installing actionmailer 5.1.3
remote:        Installing actioncable 5.1.3
remote:        Fetching sprockets-rails 3.2.0
remote:        Installing railties 5.1.3
remote:        Installing sprockets-rails 3.2.0
remote:        Fetching simple_form 3.5.0
remote:        Installing simple_form 3.5.0
remote:        Fetching coffee-rails 4.2.2
remote:        Fetching responders 2.4.0
remote:        Fetching font-awesome-rails 4.7.0.2
remote:        Installing coffee-rails 4.2.2
remote:        Installing responders 2.4.0
remote:        Fetching rails 5.1.3
remote:        Fetching sass-rails 5.0.6
remote:        Installing font-awesome-rails 4.7.0.2
remote:        Installing sass-rails 5.0.6
remote:        Installing rails 5.1.3
remote:        Fetching devise 4.3.0
remote:        Installing devise 4.3.0
remote:        Bundle complete! 26 Gemfile dependencies, 63 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        The latest bundler is 1.15.4, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote:        Bundle completed (32.58s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.15.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        The latest bundler is 1.15.4, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote: -----> Installing node-v6.11.1-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        Yarn executable was not detected in the system.
remote:        Download Yarn at https://yarnpkg.com/en/docs/install
remote:        rake aborted!
remote:        Sprockets::FileNotFound: couldn't find file 'jquery' with type 'application/javascript'
remote:        Checked in these paths:
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/app/assets/config
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/app/assets/images
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/app/assets/javascripts
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/app/assets/stylesheets
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/font-awesome-rails-4.7.0.2/app/assets/fonts
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/font-awesome-rails-4.7.0.2/app/assets/stylesheets
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/actioncable-5.1.3/lib/assets/compiled
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.3/lib/assets/compiled
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/node_modules
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/bootstrap-sass-3.3.7/assets/stylesheets
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/bootstrap-sass-3.3.7/assets/javascripts
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/bootstrap-sass-3.3.7/assets/fonts
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/bootstrap-sass-3.3.7/assets/images
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/app/assets/javascripts/application.js:13
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in `resolve'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
remote:        /tmp/build_accb86056660277e88ce60d1b5714034/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to iccg-team-green.
remote: 
To https://git.heroku.com/iccg-team-green.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/iccg-team-green.git'
</pre></details>

**Comment by Rojo** [comment]
@jwald1 @Xiaohong-Deng Deploying on Heroku works now, but Redis configuration still needs to be set to have a working application there.

https://github.com/Xiaohong-Deng/mooqita-icccg/tree/fix/heroku-deploy

**Comment by Xiaohong-Deng** [comment]
@Rojo About redis setting on heroku, is this useful to you? https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable#step-2-provision-the-redis-to-go-addon

**Comment by Rojo** [comment]
@jwald1 @Xiaohong-Deng The Heroku configuration seems to be working but the application halts when starting a new game. The logs show the following:

```
2017-08-30T18:35:58.577774+00:00 app[web.1]: I, [2017-08-30T18:35:58.577674 #4]  INFO -- : [c4a1199d-1a10-4ace-9c67-c7331b7fa8ee] Completed 200 OK in 33ms (Views: 24.3ms | ActiveRecord: 1.9ms)
2017-08-30T18:36:00.224808+00:00 app[web.1]: I, [2017-08-30T18:36:00.224701 #4]  INFO -- : [5074c943-dca5-497d-9a00-7c4ca5346cd6] Started GET "/cable/" [WebSocket] for 177.248.145.104 at 2017-08-30 18:36:00 +0000
2017-08-30T18:36:00.241995+00:00 app[web.1]: I, [2017-08-30T18:36:00.241904 #4]  INFO -- : [ActionCable] [user4@example.com] Registered connection (Z2lkOi8vbW9vcWl0YS1pY2NjZy9Vc2VyLzQ)
2017-08-30T18:36:00.103969+00:00 app[web.1]: I, [2017-08-30T18:36:00.103871 #4]  INFO -- : [5074c943-dca5-497d-9a00-7c4ca5346cd6] Started GET "/cable" for 177.248.145.104 at 2017-08-30 18:36:00 +0000
2017-08-30T18:36:00.224948+00:00 app[web.1]: I, [2017-08-30T18:36:00.224874 #4]  INFO -- : [5074c943-dca5-497d-9a00-7c4ca5346cd6] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
2017-08-30T18:36:00.239318+00:00 app[web.1]: D, [2017-08-30T18:36:00.238990 #4] DEBUG -- :   User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
2017-08-30T18:36:00.427071+00:00 app[web.1]: E, [2017-08-30T18:36:00.426388 #4] ERROR -- : [ActionCable] [user4@example.com] Could not execute command from ({"command"=>"subscribe", "identifier"=>"{\"channel\":\"GameWaitingRoomChannel\"}"}) [Redis::CannotConnectError - Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)]: /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:345:in `rescue in establish_connection' | /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:331:in `establish_connection' | /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect' | /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect' | /app/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
2017-08-30T18:36:00.438556+00:00 app[web.1]: I, [2017-08-30T18:36:00.438432 #4]  INFO -- : [ActionCable] [user4@example.com] GameWaitingRoomChannel is streaming from game_waiting_room:Z2lkOi8vbW9vcWl0YS1pY2NjZy9Vc2VyLzQ
2017-08-30T18:36:00.438968+00:00 app[web.1]: I, [2017-08-30T18:36:00.438647 #4]  INFO -- : [ActionCable] [user4@example.com] GameWaitingRoomChannel is streaming from waiting-room
```

Seems like Redis is rejecting the connection. Any ideas?

**Comment by jwald1** [comment]
Edit line 44 and 45 in https://github.com/Xiaohong-Deng/mooqita-icccg/blob/fix/heroku-deploy/config/environments/production.rb

**Comment by jwald1** [comment]
Also, https://github.com/Xiaohong-Deng/mooqita-icccg/blob/fix/heroku-deploy/config/cable.yml Line 11 what does `ENV["REDISTOGO_URL"]` referring to?

**Comment by Rojo** [comment]
@jwald1 Sorry, the branch was not up to date. The configuration is up now, but the server still rejects the connection.

The `ENV["REDISTOGO_URL"]` refers to the URL of the Redis instance given by Heroku for the application. You can see the value in the Application > Settings > Config Vars part of the dashboard.

**Comment by jwald1** [comment]
on line 46 change the second URL to this `/http:\/\/iccg-team-green.herokuapp.com.*/`.  https://stackoverflow.com/questions/36980486/deploy-actioncable-on-heroku-rails-5-beta4

**Comment by jwald1** [comment]
@Rojo change line 4 of https://github.com/Xiaohong-Deng/mooqita-icccg/blob/fix/heroku-deploy/app/models/game_waiting_room.rb to this

```ruby
def initialize(queue: Redis::Unique::Queue.new('game_waiting_room', Redis.new(url: ENV['REDISTOGO_URL']))
```
I'll later improve the code

**Comment by jwald1** [comment]
Should I commit the fix to this branch directly?

**Comment by Rojo** [comment]
@jwald1 You mean the refactor? Why not? Just let me know to double check that it works correctly when deployed.

**Comment by Rojo** [comment]
Fixed with https://github.com/Xiaohong-Deng/mooqita-icccg/pull/26
