### ISSUE TITLE
Allow player to leave a game

### ISSUE THREAD

**Issue by Rojo** [Xiaohong-Deng/mooqita-icccg#27]
On the **waiting for players** screen, if a player clicks on **leave game**, the user's clable connection is closed...

![image](https://user-images.githubusercontent.com/92138/29947948-ca6bce26-8e71-11e7-9d2d-fdf690362e25.png)

...and the browser returns to the **start game** screen.

![image](https://user-images.githubusercontent.com/92138/29954048-905d35d4-8e9a-11e7-9588-66a2ad54b351.png)

**Comment by Xiaohong-Deng** [comment]
Leave the waiting room page yes. technically you always have a connection as long as you send a request to the server.

**Comment by Rojo** [comment]
@Xiaohong-Deng This refers specifically to the upgraded web socket connection. I'm not sure that with a simple redirection the stream stops and the connection ends cleanly, but it may work.

**Comment by jwald1** [comment]
I've made the connection page specific, so if user leaves the connection
will end.

**Comment by Xiaohong-Deng** [comment]
@Rojo That's what I meant. Every time you send a http request, you upgrade to a web socket connection right after. Redirect to another page is also a http request. At least it's the general case.
