### ISSUE TITLE
Allow player to send invitations to join a game

### ISSUE THREAD

**Issue by Rojo** [Xiaohong-Deng/mooqita-icccg#28]
On the **waiting for players** screen, if a player clicks on _invite players_, it should be able to send invitations to join a game.

![image](https://user-images.githubusercontent.com/92138/29954212-dc1b903c-8e9b-11e7-8059-c9489d247a05.png)

**Comment by Rojo** [comment]
@Xiaohong-Deng @jwald1 How is this going the be managed? The invitations should be by email sharing a game url or should it be only to other application's users via notifications?

**Comment by jwald1** [comment]
Should be via email and providing a URL. There is no game at that point.

**Comment by Xiaohong-Deng** [comment]
@Rojo @jwald1 Sending emails to all other users sounds pretty annoying and not likely will get you what you want. It should be easy to do though.

**Comment by Xiaohong-Deng** [comment]
@Rojo make sure to prevent users from sending 500 email in 1 min through rapid firing. still think we shouldn't implement this.

**Comment by Rojo** [comment]
@Xiaohong-Deng Dou you mean that we should remove the invitation feature completely?

**Comment by Xiaohong-Deng** [comment]
@Rojo not necessarily. it's an enhancement that won't affect the main process of the game. it's just my personal opinion that sending email brings bad UX and won't get more participation. but implementing it doesn't hurt.

**Comment by Rojo** [comment]
@Xiaohong-Deng Well, I can set it as future enhancement and leave it pending, but then we should hide the _invite players_ button. How about it?

**Comment by Xiaohong-Deng** [comment]
@Rojo Sounds good. doesn't really matter we hide the button or not. we have dummy links in other places, too. leaving it be is just fine.

**Comment by Rojo** [comment]
@Xiaohong-Deng OK, I'll move to get more knowledgeable on Action Cable for the other required features.

**Comment by Xiaohong-Deng** [comment]
well. my opinon on this is
1. sending email could be annoying, likely to be filtered by spam filter.
2. whom to send to? allow users in the site? annoying again. only friends? so we need to build a twitter like follower-following system? just too much implications for this feature.
