### ISSUE TITLE
What should happen when a player leaves a game in course?

### ISSUE THREAD

**Issue by Rojo** [Xiaohong-Deng/mooqita-icccg#31]
@jwald1 @Xiaohong-Deng  I've been poking around a noticed that when a player leaves a game that has already started (currently by requesting other URL on the browser address bar), the other players remain on the game screen.

Also, if the player that left clicks the start game button, it will take him/her to the waiting screen to start a new game. (Which seems OK.)

So the questions are:

- What should happen on the remaining players' screens when a player leaves (or loses connection)?
- How can we handle a player rejoining a game? (Should other be able to player take its place?).

**Comment by Xiaohong-Deng** [comment]
@Rojo 

1. if a player leaves, end the game and redirect the other players could be one way to handle it. if a player loses connection, actioncable has the mechanism to reconnect or give up after trying for a short time interval. I am not able to code it now.
2. invite another player is inappropriate. what if the game has passed many rounds, isn't it unfair for the new comer?

**Comment by Xiaohong-Deng** [comment]
with asynchronous gameplay in place, I don't think this question is relevant anymore
