### ISSUE TITLE
enter the gaming cycle

### ISSUE THREAD

**Issue by Xiaohong-Deng** [Xiaohong-Deng/mooqita-icccg#34]
Once there are 3 players in the waiting room, they should be auto redirected to the 1st page of the gaming cycle.

The roles should be assigned to players once they arrive the page, and the questioner should be assigned. Questioner should have input text area on the page. Judge and reader should have doc shown on the page.

The feature is done once 3 players reach the correct pages for them respectively.

**Comment by Rojo** [comment]
I've finished following the [tutorial](https://www.learnenough.com/action-cable-tutorial#cha-action_cable) for action cable.

Seems that several streams will be needed for each game:

- **Main stream**: Provide information about the game status (whose turn is it, whiteboard, scores).
- **Guesses stream**: Allow the guesser to input questions and answers.
- **Reader stream**: Allow the guesser to input questions and answers, and receive the document information.
- **Judge stream**: Allow the judge to receive questions and answers, guess the _reader_ and receive the document information.

The streams could take their name from the game id and the role like:

- `game_#{game.id}`
- `game_#{game.id}_guesser`
- `game_#{game.id}_reader`
- `game_#{game.id}_judge`

On every turn, the game would randomly pick one of the guesser or reader streams and send the _new question_ from through it.

**Comment by Xiaohong-Deng** [comment]
Yes. multiple streams are a plausible strategy. The tricky part is the
javascript/jQuery ac introduced which is what's I've been working on for
the past several days.
I thought about it. The game logic and the back end logic are no big deal.
It's the js to interact with them that I'm not sure of.
Anyway, I still have Jacob's code to read. Hope can produce something asap.

**Comment by Xiaohong-Deng** [comment]
I read the code more. I think based on Jacob's design, players should click start_game button on their own.
