### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by Rojo** [Xiaohong-Deng/mooqita-icccg#4]
Ubuntu image with Vagrant over Virtualbox.

**Comment by Xiaohong-Deng** [comment]
@Rojo Can you explain this issue? Is this a potential feature/story that can be applied to the app?.

**Comment by Rojo** [comment]
Is a devop step to allow all the developers share the same virtual development environment, independent of the operating system on their computers.

**Comment by Rojo** [comment]
See https://github.com/Rojo/vagrant-for-rails

**Comment by Xiaohong-Deng** [comment]
@Rojo You sure others agree with this setting? For example, Ruby 2.4. I start this project with 2.3.1. How about using Gemfile to synchronous the dev environment? Use `sqlite3` in development and `pg` in heroku, like we did in cs169.1x?

**Comment by Rojo** [comment]
The virtual environment is totally customizable. It just provides the tools, the project itself is the one that specifies the versions to be used.

**Comment by Xiaohong-Deng** [comment]
@Rojo I see. You want to provide others with the option to automatically install the dependencies. I have no problem with that.
