### ISSUE TITLE
Start a new Game or Join an Existing

### ISSUE THREAD

**Issue by jwald1** [Xiaohong-Deng/mooqita-icccg#5]
As a logged in user
I want to be able to start a new game or join an existing game

**Comment by Xiaohong-Deng** [comment]
@jwald1 I have a vision that when a user logs in, he or she should be directed to a page shows him or her 2 buttons. Namely, `Create a Game` and `Join a Game`. If he clicks `Create a Game` he should be directed to a page showing him 3 slots and buttons to launch or cancel the game.

If he clicks `Join a Game`, he should be directed to a page showing him a list of waiting games. It could be an unodered list. We should decide how many games should be shown on one page. Thus, pagination could be useful here. `gem will_paginate`, `gem bootstrap-will_paginate` are such gems.

That's my two cents on this feature so far. Hope it's useful and open to any suggestions.

**Comment by jwald1** [comment]
I think for now we should just allow a user to join a queue if there is no queue the system will create a new queue. Here is my mockup. I'm still in the planning process, so it's hard for to explain all the details yet.
[start_game.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598a35d4a585de001a0271d2/125516c66e82c728ace21e0d46fb809b3196bcae8ee4ba01e81fe086264c22703d46f96925dcbb71ba1b7a500e5746f9495e5f44fff0887aa3b73a75984019af80330b2b9b645bf9fa9015ad03bc2a8a4a85b5bc834ec2ed3b2def839d02.pdf)

**Comment by jwald1** [comment]
@Xiaohong-Deng if you can implement the HTML/CSS it will be a big help.

**Comment by Xiaohong-Deng** [comment]
@jwald1 You mean the css styling? That could wait. If you want me to build the templates from scratch, i can't do it for you. it's tightly coupled with your backend.

**Comment by jwald1** [comment]
I've refactored the join feature to join-game-queue-action-cable branch. It's almost ready still need to add a description and tests. Please check it out.
You will need Redis and Yarn installed on your machine and run `rake yarn:install`
